# Generated by Django 2.1.5 on 2021-09-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_gc_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_num', models.IntegerField()),
                ('plot_size', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
