# Generated by Django 2.1.5 on 2021-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyn_gc_App', '0002_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_size',
            field=models.CharField(max_length=20),
        ),
    ]
